<a href="https://colab.research.google.com/github/Natansh2005/100-Days-OF-ML/blob/main/web_Scraping_Day_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [11]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://internshala.com/internships/engineering-internship/page-1', headers=headers).text

In [6]:
requests.get('https://internshala.com/internships/engineering-internship/page-1').text

'<!DOCTYPE html>\n    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml"\n        lang="en">\n\n<head>\n    <meta http-equiv="X-UA-Compatible" content="IE=9" />\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=0" />\n    <meta property="fb:app_id" content="702141670710132" />\n    <meta property="og:type" content="website" />\n            <meta property="og:image:width" content="1200" />\n        <meta property="og:image:height" content="630" />\n        <link rel="preload" href="https://internshala.com//static/images/home/sprites/img-assets.png" as="image"/>\n<link rel="preload" as="image" href="https://internshala.com/static/images/internship/banners/jobs_banner_r767.png" media="(max-width: 767px)"/>\n<link rel="preload" as="image" href="https://internshala.com/static/images/internship/banners/jobs_banner_r1920.png" media="(min-width: 767.1px)"/>\n\n<link rel="preload" as="image" href="https://internshala.com/static/images/internship/subscription-popup/r575.png" media="(min-width: 767.1px)"/>\n<link rel="preload" as="image" href="https://internshala.com/static/images/internship/subscription-popup/r1920.png" media="(max-width: 767px)"/>    <meta name="twitter:site" content="@Internshala" />\n            <meta name="twitter:card" content="summary_large_image" />\n    \n    <meta name="twitter:creator" content="@internshala" />\n        <meta name="theme-color" content="#ffffff" />\n    <meta name="msapplication-navbutton-color" content="#ffffff" />\n    <meta name="format-detection" content="telephone=no" />\n\n            <link as="font" href="/static/fonts/Inter.woff2?v=3.11" type="font/woff2" crossorigin />\n            <link as="font" href="/static/fonts/internshala-icons.woff2?vw3rgh" type="font/woff2"  crossorigin />    <script src="/static/js/web_vitals/web-vitals.umd.js"></script>\n            <script src="/static/js/includes/common/libraries.2583691470.js" defer></script>\n                <link rel="stylesheet" href="https://internshala.com//static/cdn/4.4.1/css/bootstrap.min.css" />\n        \n    <link rel="icon" href="https://internshala.com//favicon.ico?v=5" />\n    <script nonce="qvtqkfOxpFSMNpEQeA29BA==">\n        var os_type = "";\n        var browser_name = \'python\';\n        var is_android = 0;\n        var is_mobile = 1;\n        var l_cookie = "";\n        var view = "internship/search/search";\n        var user_id_ga = 0;\n        var mainRole = "guest";\n        var to_show_account_activated_message = false;\n        var to_show_subscription_activated_message = false;\n        var location_autocomplete_min_length = 3;\n        var fresherJobsMinCtc = 2;\n        var show_maintenance_ribbon = false;\n        var maintenance_ribbon_message = "";\n        var base_url = \'https://internshala.com/\';\n        var bulk_request_url_with_trailing_slash = \'https://internshala.com/\';\n        var is_g_recaptcha = "6Lcqj0EsAAAAAL4K2T7--kNrAXT3_99tIuEQLZJF";\n        var error_ribbon_support_email = "support@internshala.com";\n</script>\n            <title >Engineering Internships: Find 856 Engineering Intern Jobs</title>\n        <meta name="description" content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" />\n        <meta property="og:title" content="Engineering Internships: Find 856 Engineering Intern Jobs" />\n        <meta property="og:description" content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" />\n        <meta property="og:image" content="https://internshala.com//static/images/internships_for_facebook.png" />\n        <meta name="twitter:title" content="Engineering Internships: Find 856 Engineering Intern Jobs" />\n        <meta name="twitter:description" content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" />\n        <meta property="twitter:image:src" content="https://internshala.com//static/images/internships_for_facebook.png" />\n        <link href="/static/css/internship/search/search.1775554316.css" rel="stylesheet" type="text/css" />\n        <script src="/static/js/combined/common_form.1773211830.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/combined/internship-search.1772430925.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/subscribe/popup.1727159863.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/student/carousel.1736162514.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/review_section.1727159863.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/student/app_download.1732685003.js" defer="" type="text/javascript" ></script>\n        <script src="/static/js/footer.1760584489.js" defer="" type="text/javascript" ></script>\n        <script src="https://www.google.com/recaptcha/enterprise.js?render=6Lcqj0EsAAAAAL4K2T7--kNrAXT3_99tIuEQLZJF" defer="" type="text/javascript" ></script>\n    <link rel=\'next\' href=\'internships/engineering-internship/page-2/\'/>\n<link rel=\'canonical\' href=\'https://internshala.com/internships/engineering-internship/\'/>\n    <script nonce="qvtqkfOxpFSMNpEQeA29BA==">\n    function sendToGTM(name, delta, id) {\n        if (typeof dataLayer == \'undefined\') {\n            return;\n        }\n        // Assumes the global `dataLayer` array exists, see:\n        // https://developers.google.com/tag-manager/devguide\n        dataLayer.push({\n            event: \'web-vitals\',\n            event_category: \'Web Vitals\',\n            event_action: name.name,\n            // Google Analytics metrics must be integers, so the value is rounded.\n            // For CLS the value is first multiplied by 1000 for greater precision\n            // (note: increase the multiplier for greater precision if needed).\n            event_value: Math.round(name.name === \'CLS\' ? name.delta * 1000 : name.delta),\n            // The \'id\' value will be unique to the current page load. When sending\n            // multiple values from the same page (e.g. for CLS), Google Analytics can\n            // compute a total by grouping on this ID (note: requires `eventLabel` to\n            // be a dimension in your report).\n            event_label: name.id,\n        });\n    }\n    webVitals.getCLS(sendToGTM);\n    webVitals.getFID(sendToGTM);\n    webVitals.getLCP(sendToGTM);\n    webVitals.getFCP(sendToGTM);\n    webVitals.getTTFB(sendToGTM);\n</script>\n<script nonce="qvtqkfOxpFSMNpEQeA29BA==">\n//    window.addEventListener(\'load\', function() {\n//        store_session_data();\n//    });\n\n//    window.addEventListener(\'DOMContentLoaded\', function() {\n//        store_session_data();\n//    });\n\n    var pdcVersion = "0";\n    var toMakeInitialRequest = 1;\n    if (toMakeInitialRequest == 1) {\n        store_session_data();\n    }\n\n    function store_session_data() {\n        var message = "device=" + getDeviceType();\n        var xhttp = new XMLHttpRequest();\n        xhttp.onreadystatechange = function () {\n            if (this.readyState === 4 && this.status === 200) {\n                //Success\n                var responseText = this.responseText;\n                try {\n                    data = JSON.parse(responseText);\n                    if (data.success) {\n                        if(data.toMakeUpdateRequest) {\n                            update_session_data();\n                        }\n                    } else {\n                        //TODO\n                    }\n                } catch (e) {\n                    throw_error(e);\n                }\n            }\n        };\n\n        xhttp.open("POST", "/info/storeData", true);\n        xhttp.setRequestHeader(\'X-Requested-With\', \'XMLHttpRequest\');\n        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");\n        xhttp.send(message);\n    }\n\n    function update_session_data() {\n        var message = "";\n        var xhttp = new XMLHttpRequest();\n        xhttp.onreadystatechange = function () {\n            if (this.readyState === 4 && this.status === 200) {\n                //Success\n            }\n        };\n\n        xhttp.open("POST", "/info/updateDeviceCookieVersion", true);\n        xhttp.setRequestHeader(\'X-Requested-With\', \'XMLHttpRequest\');\n        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");\n        xhttp.send(message);\n    }\n\n    function getDeviceType() {\n        var device;\n        if (typeof isMobile !== \'undefined\') {\n            if (isMobile === \'1\') {\n                device = "mobile";\n            } else {\n                device = "desktop";\n            }\n        } else {\n            device = "NA";\n        }\n\n        return device;\n    }\n\n</script>\n    <script nonce="qvtqkfOxpFSMNpEQeA29BA==">\n        if (typeof Moengage !== \'undefined\') {\n            const page_type_for_moengage_view = \'internship_search_page\';\n            if (page_type_for_moengage_view) {\n                Moengage.track_event(`${page_type_for_moengage_view}_visits`);\n            }\n        }\n    </script>\n        <script nonce="qvtqkfOxpFSMNpEQeA29BA==">\n        var junk_domain_data = {};\n\n            </script>\n        </head>\n\n<body>\n            <div id="wrapper">\n        <!-- ribbon -->\n<div id=\'error\' class="notification">\n</div>\n\n<div id=\'general_notification\' class="notification notification_general" style="display: none">\n</div>\n\n<div id="custom_notification_parent">\n    <div id=\'custom_notification\' class="notification notification_general" style="display: none">\n    </div>\n</div>\n\n<!-- modal - error message -->\n<div id="error_modal" class="modal fade in internshala-modal" style="display: none">\n    <div class="modal-dialog">\n        <div class="modal-content">\n            <div class="modal-body">\n                <div class="image_container error_image">\n                    <div class="image"></div>\n                </div>\n                <div class="message_container">\n                    <div class="text-heading heading_4_5 small-device-text-center"></div>\n                    <div class="text-message body-main small-device-text-center"></div>\n                    <div class="button_container">\n                        <a class="btn btn-primary modal_primary_btn close_action" data-dismiss= "modal">Close</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n\n<!-- modal - success message -->\n<div id="success_modal" class="modal fade in internshala-modal" style="display: none">\n    <div class="modal-dialog">\n        <div class="modal-content">\n            <div class="modal-body">\n                <div class="image_container success_image">\n                    <div class="image"></div>\n                </div>\n                <div class="message_container">\n                    <div class="text-heading heading_4_5 small-device-text-center"></div>\n                    <div class="text-message body-main small-device-text-center"></div>\n                    <div class="button_container">\n                        <button class="btn btn-secondary modal_secondary_btn close_action" data-dismiss= "modal">Cancel</button>\n                        <a class="btn btn-primary modal_primary_btn close_action" data-dismiss= "modal">Close</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n<!-- modal - success message -->\n<div id="success_modal_dual_button" class="modal fade in internshala-modal" style="display: none">\n    <div class="modal-dialog">\n        <div class="modal-content">\n            <div class="modal-body">\n                <div class="image_container success_image">\n                    <div class="image"></div>\n                </div>\n                <div class="message_container">\n                    <div class="text-heading heading_4_5 small-device-text-center"></div>\n                    <div class="text-message body-main small-device-text-center"></div>\n                    <div class="button_container">\n                        <a class="btn btn-secondary modal_secondary_btn close_action" data-dismiss= "modal">Close</a>\n                        <a class="btn btn-primary modal_primary_btn close_action" data-dismiss= "modal">Close</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n\n<!-- modal - alert message -->\n<div id="alert_modal" class="modal fade in internshala-modal" style="display: none">\n    <div class="modal-dialog">\n        <div class="modal-content">\n            <div class="modal-body">\n                <div class="image_container alert_image">\n                    <div class="image"></div>\n                </div>\n                <div class="message_container">\n                    <div class="text-heading heading_4_5 small-device-text-center"></div>\n                    <div class="text-message body-main small-device-text-center"></div>\n                    <div class="button_container">\n                        <a class="btn btn-primary modal_primary_btn close_action" data-dismiss= "modal">Close</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n\n<!--- confirmation modal-->\n<div id="confirmation_modal" class="modal fade in internshala-modal confirmation_modal" style="display: none">\n    <div class="modal-dialog">\n        <div class="modal-content">\n            <div class="modal-body">\n                <div class="message_container">\n                    <div class="text-heading heading_4_5"></div>\n                    <div class="text-message body-main"></div>\n                    <div class="button_container">\n                        <button class="btn btn-secondary modal_secondary_btn close_action" data-dismiss= "modal">Cancel</button>\n                        <a class="btn btn-primary modal_primary_btn yes-button close_action" data-dismiss= "modal">Yes</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n\n<div class="loading_image">\n</div>\n\n<div class="nav_dropdown_backdrop ">\n</div>\n\n    <noscript>\n    <div class="notification notification_js_disabled" style="display: block;">\n        Oops, your browser does not support Javascript. Please use Internshala in another browser.\n    </div>\n    </noscript>\n    \n<div class="toast internshala-toast loading_toast" id="loading_toast" style="display: none;">\n    <div class="toast-body-container">\n        <div class="toast-body heading_6_6">\n            Loading, please wait...\n        </div>\n    </div>\n</div>\n\n<div class="toast internshala-toast general_toast" style="display: none;">\n    <div class="toast-body-container">\n        <div class="toast-body heading_6_6">\n        </div>\n    </div>\n</div>\n\n<div class="toast internshala-toast success_toast" style="display: none;">\n    <div class="toast-body-container">\n        <div class="toast-body heading_6_6">\n        </div>\n    </div>\n</div>\n\n<div class="toast internshala-toast error_toast" style="display: none;">\n    <div class="toast-body-container">\n        <div class="toast-body heading_6_6">\n        </div>\n    </div>\n</div>\n\n<div class="toast internshala-toast black_bottom_toast" style="display: none;">\n    <div class="toast-body-container">\n        <div class="toast-body body-main">\n        </div>\n    </div>\n</div>\n\n<div class="popover_overlay">\n</div>\n\n\n<div class="chat_notification_loading_image" style="display: none;">\n</div>\n    <div class="modal " id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">\n        <div class="modal-dialog">\n            <div class="modal-content">\n                <div class="modal-header">\n                    <button type="button" class="close" data-dismiss="modal">\n                        <i class="ic-24-cross" aria-hidden="true"></i>\n                    </button>\n                </div>\n                <div class="modal-body ">\n                            <div id="user-menu-container">\n                            <div id="user-menu">\n                                <div class="row">\n                                    <div class="col-xs-6 col-6 user-menu-item active login_student" id="modal_student">\n                                        Student\n                                    </div>\n                                    <div class="col-xs-6 col-6 user-menu-item login_employer" id="modal_employer">\n                                        Employer / T&P\n                                    </div>\n                                </div>\n                            </div>\n                        </div>\n                                                    <a class="google_login" id="user_google_login" href="/login/get_google/student" >\n\n                                <div id="google-button-container" data-source="google_login_modal">\n                                    <div class="google_image_container">\n                                        <div class=\'google_logo\'></div>\n                                    </div>\n                                    <div class="google_content">\n                                        Login with Google\n                                    </div>\n                                </div>\n                            </a>\n                        <div class="helper">\n                            <div class="text2">\n                                <p>OR</p>\n                            </div>\n                            <div class=\'border\'></div>\n                        </div>\n                    \n                    <form role="form" id="modal-login-form" method="POST">\n                        <input type="hidden" name="csrf_test_name" value="c19448092fe6786d0c566279e6646743" />\n                        <div class="form-group">\n                            <label for="email" class="control-label">Email</label>\n                            <input type="email" class="form-control" id="modal_email" tabindex="1" name="email" placeholder="john@example.com">\n                        </div>\n                        <div class="form-group">\n                            <label for="password" class="control-label">Password</label>\n                            <input type="password" class="form-control" id="modal_password" tabindex="2" name="password" placeholder="Must be atleast 6 characters" autocomplete="current-password">\n                        </div>\n                        <div class="forgot_password">\n                            <a href="/login/forgot_password" id="forgot-password">Forgot password?</a>\n                        </div>\n                        <div class="form-group">\n                            <button type="submit" class="btn btn-primary" id="modal_login_submit" tabindex="3">Login</button>\n                        </div>\n                                <div class="form-group new_to_internshala">\n                                <label>\n                                    New to Internshala? Register (<a href=\'/registration/student\'>Student</a> / <a href="/hire-talent">Company</a>)\n                                </label>\n                            </div>\n                                            </form>\n                </div>\n            </div>\n        </div>\n    </div>\n\n<!-- Login modal - error message for employers blo

In [12]:
soup=BeautifulSoup(webpage, 'lxml')

In [13]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
 <head>
  <meta content="IE=9" http-equiv="X-UA-Compatible"/>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0 user-scalable=0" name="viewport"/>
  <meta content="702141670710132" property="fb:app_id"/>
  <meta content="website" property="og:type"/>
  <meta content="1200" property="og:image:width"/>
  <meta content="630" property="og:image:height"/>
  <link as="image" href="https://internshala.com//static/images/home/sprites/img-assets.png" rel="preload"/>
  <link as="image" href="https://internshala.com/static/images/internship/banners/jobs_banner_r767.png" media="(max-width: 767px)" rel="preload"/>
  <link as="image" href="https://internshala.com/static/images/internship/banners/jobs_banner_r1920.png" media="(min-width: 767.1px)" rel="preload"/>
  <link as="image" href="https://internshala.com/static/images/internship/subscription-popup/r575.png" media="(min-width: 767.1px)" rel="preload"/>
  <link as="image" href="https://internshala.com/static/images/internship/subscription-popup/r1920.png" media="(max-width: 767px)" rel="preload"/>
  <meta content="@Internshala" name="twitter:site"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@internshala" name="twitter:creator"/>
  <meta content="#ffffff" name="theme-color"/>
  <meta content="#ffffff" name="msapplication-navbutton-color"/>
  <meta content="telephone=no" name="format-detection"/>
  <link as="font" crossorigin="" href="/static/fonts/Inter.woff2?v=3.11" type="font/woff2"/>
  <link as="font" crossorigin="" href="/static/fonts/internshala-icons.woff2?vw3rgh" type="font/woff2"/>
  <script src="/static/js/web_vitals/web-vitals.umd.js">
  </script>
  <script defer="" src="/static/js/includes/common/libraries.2583691470.js">
  </script>
  <link href="https://internshala.com//static/cdn/4.4.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="https://internshala.com//favicon.ico?v=5" rel="icon"/>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   var os_type = "Windows";
        var browser_name = 'chrome';
        var is_android = 0;
        var is_mobile = 0;
        var l_cookie = "";
        var view = "internship/search/search";
        var user_id_ga = 0;
        var mainRole = "guest";
        var to_show_account_activated_message = false;
        var to_show_subscription_activated_message = false;
        var location_autocomplete_min_length = 3;
        var fresherJobsMinCtc = 2;
        var show_maintenance_ribbon = false;
        var maintenance_ribbon_message = "";
        var base_url = 'https://internshala.com/';
        var bulk_request_url_with_trailing_slash = 'https://internshala.com/';
        var is_g_recaptcha = "6Lcqj0EsAAAAAL4K2T7--kNrAXT3_99tIuEQLZJF";
        var error_ribbon_support_email = "support@internshala.com";
  </script>
  <title>
   Engineering Internships: Find 856 Engineering Intern Jobs
  </title>
  <meta content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" name="description"/>
  <meta content="Engineering Internships: Find 856 Engineering Intern Jobs" property="og:title"/>
  <meta content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" property="og:description"/>
  <meta content="https://internshala.com//static/images/internships_for_facebook.png" property="og:image"/>
  <meta content="Engineering Internships: Find 856 Engineering Intern Jobs" name="twitter:title"/>
  <meta content="Apply for 856+ engineering internships on Internshala. Find the latest paid internship for engineering students and get your dream job today!" name="twitter:description"/>
  <meta content="https://internshala.com//static/images/internships_for_facebook.png" property="twitter:image:src"/>
  <link href="/static/css/internship/search/search.1775554316.css" rel="stylesheet" type="text/css"/>
  <script defer="" src="/static/js/combined/common_form.1773211830.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/combined/internship-search.1772430925.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/subscribe/popup.1727159863.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/student/carousel.1736162514.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/review_section.1727159863.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/student/app_download.1732685003.js" type="text/javascript">
  </script>
  <script defer="" src="/static/js/footer.1760584489.js" type="text/javascript">
  </script>
  <script defer="" src="https://www.google.com/recaptcha/enterprise.js?render=6Lcqj0EsAAAAAL4K2T7--kNrAXT3_99tIuEQLZJF" type="text/javascript">
  </script>
  <link href="internships/engineering-internship/page-2/" rel="next"/>
  <link href="https://internshala.com/internships/engineering-internship/" rel="canonical"/>
  <!-- Google Tag Manager -->
  <script data-dsn="V7/hrQAJa22M4lgLHJ4lTw==" id="gtmScript" nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;var n=d.querySelector('[nonce]');
        n&&j.setAttribute('nonce',n.nonce||n.getAttribute('nonce'));f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5NSPHG');
  </script>
  <!-- End Google Tag Manager -->
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==" type="text/javascript">
   var moeDataCenter = "dc_3"; // Replace "DC" with the actual Data center value from the above table
	var moeAppID = "H2AZG7O4X4KYQ8C362UKNTNW"; // Replace "WorkspaceID" available in the settings page of MoEngage Dashboard.
	var sdkVersion = "2.54.12"; // Replace this value with the version of Web SDK that you intend to use. It is recommended to use the format x (major)

	!function(e,n,i,t,a,r,o,d){if(!moeDataCenter||!moeDataCenter.match(/^dc_[0-9]+$/gm))return console.error("Data center has not been passed correctly. Please follow the SDK installation instruction carefully.");var s=e[a]=e[a]||[];if(s.invoked=0,s.initialised>0||s.invoked>0)return console.error("MoEngage Web SDK initialised multiple times. Please integrate the Web SDK only once!"),!1;e.moengage_object=a;var l={},g=function n(i){return function(){for(var n=arguments.length,t=Array(n),a=0;a<n;a++)t[a]=arguments[a];(e.moengage_q=e.moengage_q||[]).push({f:i,a:t})}},u=["track_event","add_user_attribute","add_first_name","add_last_name","add_email","add_mobile","add_user_name","add_gender","add_birthday","destroy_session","add_unique_user_id","update_unique_user_id","moe_events","call_web_push","track","location_type_attribute"],m={onsite:["getData","registerCallback"]};for(var c in u)l[u[c]]=g(u[c]);for(var v in m)for(var f in m[v])null==l[v]&&(l[v]={}),l[v][m[v][f]]=g(v+"."+m[v][f]);r=n.createElement(i),o=n.getElementsByTagName("head")[0],r.async=1,r.src=t,o.appendChild(r),e.moe=e.moe||function(){return(s.invoked=s.invoked+1,s.invoked>1)?(console.error("MoEngage Web SDK initialised multiple times. Please integrate the Web SDK only once!"),!1):(d=arguments.length<=0?void 0:arguments[0],l)},r.addEventListener("load",function(){if(d)return e[a]=e.moe(d),e[a].initialised=e[a].initialised+1||1,!0}),r.addEventListener("error",function(){return console.error("Moengage Web SDK loading failed."),!1})}(window,document,"script","https://cdn.moengage.com/release/"+moeDataCenter+"/versions/"+sdkVersion+"/moe_webSdk.min.latest.js","Moengage");

	Moengage = moe({
	  app_id: moeAppID,
	  debug_logs: 0	});
	window.addEventListener('pageshow', (event) = {
	  // Send another pageview if the page is restored from bfcache.
	//   if (event.persisted) {
	//     Moengage.track_page_view();
	//   }
	});
  </script>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   function sendToGTM(name, delta, id) {
        if (typeof dataLayer == 'undefined') {
            return;
        }
        // Assumes the global `dataLayer` array exists, see:
        // https://developers.google.com/tag-manager/devguide
        dataLayer.push({
            event: 'web-vitals',
            event_category: 'Web Vitals',
            event_action: name.name,
            // Google Analytics metrics must be integers, so the value is rounded.
            // For CLS the value is first multiplied by 1000 for greater precision
            // (note: increase the multiplier for greater precision if needed).
            event_value: Math.round(name.name === 'CLS' ? name.delta * 1000 : name.delta),
            // The 'id' value will be unique to the current page load. When sending
            // multiple values from the same page (e.g. for CLS), Google Analytics can
            // compute a total by grouping on this ID (note: requires `eventLabel` to
            // be a dimension in your report).
            event_label: name.id,
        });
    }
    webVitals.getCLS(sendToGTM);
    webVitals.getFID(sendToGTM);
    webVitals.getLCP(sendToGTM);
    webVitals.getFCP(sendToGTM);
    webVitals.getTTFB(sendToGTM);
  </script>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   //    window.addEventListener('load', function() {
//        store_session_data();
//    });

//    window.addEventListener('DOMContentLoaded', function() {
//        store_session_data();
//    });

    var pdcVersion = "2";
    var toMakeInitialRequest = 1;
    if (toMakeInitialRequest == 1) {
        store_session_data();
    }

    function store_session_data() {
        var message = "device=" + getDeviceType();
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                //Success
                var responseText = this.responseText;
                try {
                    data = JSON.parse(responseText);
                    if (data.success) {
                        if(data.toMakeUpdateRequest) {
                            update_session_data();
                        }
                    } else {
                        //TODO
                    }
                } catch (e) {
                    throw_error(e);
                }
            }
        };

        xhttp.open("POST", "/info/storeData", true);
        xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send(message);
    }

    function update_session_data() {
        var message = "";
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                //Success
            }
        };

        xhttp.open("POST", "/info/updateDeviceCookieVersion", true);
        xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send(message);
    }

    function getDeviceType() {
        var device;
        if (typeof isMobile !== 'undefined') {
            if (isMobile === '1') {
                device = "mobile";
            } else {
                device = "desktop";
            }
        } else {
            device = "NA";
        }

        return device;
    }
  </script>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   if (typeof Moengage !== 'undefined') {
            const page_type_for_moengage_view = 'internship_search_page';
            if (page_type_for_moengage_view) {
                Moengage.track_event(`${page_type_for_moengage_view}_visits`);
            }
        }
  </script>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==">
   var junk_domain_data = {};
  </script>
  <script nonce="V7/hrQAJa22M4lgLHJ4lTw==" type="text/javascript">
   (function (c, l, a, r, i, t, y) {
                c[a] = c[a] || function () {
                    (c[a].q = c[a].q || []).push(arguments)
                };
                t = l.createElement(r);
                t.async = 1;
                t.src = "https://www.clarity.ms/tag/" + i;
                y = l.getElementsByTagName(r)[0];
                y.parentNode.insertBefore(t, y);
            })(window, document, "clarity", "script", "gz5kd3abd6");
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5NSPHG" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <div id="wrapper">
   <!-- ribbon -->
   <div class="notification" id="error">
   </div>
   <div class="notification notification_general" id="general_notification" style="display: none">
   </div>
   <div id="custom_notification_parent">
    <div class="notification notification_general" id="custom_notification" style="display: none">
    </div>
   </div>
   <!-- modal - error message -->
   <div class="modal fade in internshala-modal" id="error_modal" style="display: none">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-body">
       <div class="image_container error_image">
        <div class="image">
        </div>
       </div>
       <div class="message_container">
        <div class="text-heading heading_4_5 small-device-text-center">
        </div>
        <div class="text-message body-main small-device-text-center">
        </div>
        <div class="button_container">
         <a class="btn btn-primary modal_primary_btn close_action" data-dismiss="modal">
          Close
         </a>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!-- modal - success message -->
   <div class="modal fade in internshala-modal" id="success_modal" style="display: none">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-body">
       <div class="image_container success_image">
        <div class="image">
        </div>
       </div>
       <div class="message_container">
        <div class="text-heading heading_4_5 small-device-text-center">
        </div>
        <div class="text-message body-main small-device-text-center">
        </div>
        <div class="button_container">
         <button class="btn btn-secondary modal_secondary_btn close_action" data-dismiss="modal">
          Cancel
         </button>
         <a class="btn btn-primary modal_primary_btn close_action" data-dismiss="modal">
          Close
         </a>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!-- modal - success message -->
   <div class="modal fade in internshala-modal" id="success_modal_dual_button" style="display: none">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-body">
       <div class="image_container success_image">
        <div class="image">
        </div>
       </div>
       <div class="message_container">
        <div class="text-heading heading_4_5 small-device-text-center">
        </div>
        <div class="text-message body-main small-device-text-center">
        </div>
        <div class="button_container">
         <a class="btn btn-secondary modal_secondary_btn close_action" data-dismiss="modal">
          Close
         </a>
         <a class="btn btn-primary modal_primary_btn close_action" data-dismiss="modal">
          Close
         </a>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!-- modal - alert message -->
   <div class="modal fade in internshala-modal" id="alert_modal" style="display: none">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-body">
       <div class="image_container alert_image">
        <div class="image">
        </div>
       </div>
       <div class="message_container">
        <div class="text-heading heading_4_5 small-device-text-center">
        </div>
        <div class="text-message body-main small-device-text-center">
        </div>
        <div class="button_container">
         <a class="btn btn-primary modal_primary_btn close_action" data-dismiss="modal">
          Close
         </a>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!--- confirmation modal-->
   <div class="modal fade in internshala-modal confirmation_modal" id="confirmation_modal" style="display: none">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-body">
       <div class="message_container">
        <div class="text-heading heading_4_5">
        </div>
        <div class="text-message body-main">
        </div>
        <div class="button_container">
         <button class="btn btn-secondary modal_secondary_btn close_action" data-dismiss="modal">
          Cancel
         </button>
         <a class="btn btn-primary modal_primary_btn yes-button close_action" data-dismiss="modal">
          Yes
         </a>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="loading_image">
   </div>
   <div class="nav_dropdown_backdrop">
   </div>
   <noscript>
    <div class="notification notification_js_disabled" style="display: block;">
     Oops, your browser does not support Javascript. Please use Internshala in another browser.
    </div>
   </noscript>
   <div class="toast internshala-toast loading_toast" id="loading_toast" style="display: none;">
    <div class="toast-body-container">
     <div class="toast-body heading_6_6">
      Loading, please wait...
     </div>
    </div>
   </div>
   <div class="toast internshala-toast general_toast" style="display: none;">
    <div class="toast-body-container">
     <div class="toast-body heading_6_6">
     </div>
    </div>
   </div>
   <div class="toast internshala-toast success_toast" style="display: none;">
    <div class="toast-body-container">
     <div class="toast-body heading_6_6">
     </div>
    </div>
   </div>
   <div class="toast internshala-toast error_toast" style="display: none;">
    <div class="toast-body-container">
     <div class="toast-body heading_6_6">
     </div>
    </div>
   </div>
   <div class="toast internshala-toast black_bottom_toast" style="display: none;">
    <div class="toast-body-container">
     <div class="toast-body body-main">
     </div>
    </div>
   </div>
   <div class="popover_overlay">
   </div>
   <div class="chat_notification_loading_image" style="display: none;">
   </div>
   <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal" id="login-modal" role="dialog" tabindex="-1">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button class="close" data-dismiss="modal" type="button">
        <i aria-hidden="true" class="ic-24-cross">
        </i>
       </button>
      </div>
      <div class="modal-body">
       <div id="user-menu-container">
        <div id="user-menu">
         <div class="row">
          <div class="col-xs-6 col-6 user-menu-item active login_student" id="modal_student">
           Student
          </div>
          <div class="col-xs-6 col-6 user-menu-item login_employer" id="modal_employer">
           Employer / T&amp;P
          </div>
         </div>
        </div>
       </div>
       <a class="google_login" href="/login/get_google/student" id="user_google_login">
        <div data-source="google_login_modal" id="google-button-container">
         <div class="google_image_container">
          <div class="google_logo">
          </div>
         </div>
         <div class="google_content">
          Login with Google

In [ ]:
company=soup.find_all('div', class_='individual_internship')

In [17]:
soup.find_all('h1')[0].text

'856 Engineering Internships'

In [19]:
len(soup.find_all('h2'))

50

In [22]:
for i in soup.find_all('h2'):
  print(i.text.strip())

2D Game Concept Artist (Interactive)
Operations
UAV System
QA Tester
Quality Assurance & Production Manager
3D Designing (Luxury Product Design)
Mechanical Engineering
Accounting Software Tester
Web Development
Web Development
Robotics Data Engineering
Embedded Systems
Backend Development
Software Development
Front End Development
Web Development
Web Development
Game Development
CAD Design
CAD Design
Tech Support & Operations
3D Designer
Linux Engineer
Full Stack Development
Electronics Engineering
Web Development
AI And Robotics Trainer
Electrical Engineering
App Store Optimization Specialist
Python Developer
Manual Testing
DevOps
Electrical And Electronics Engineering Research Associate
IT Assistant
Python AI Developer
ReactJS Development
Biochemistry
Technical Operations
Subject Matter Expert (Civil Engineering)
AWS DevOps Engineer
Quality & Regulatory (Medical Devices)
Architecture
Mobile App Development
CAD Design
Electronics Engineering
Flutter Devlopment
Database/System Architect
Electronics Engineering
Civil Engineering
Student Volunteer

In [23]:
for i in soup.find_all('p'):
    print(i.text.strip())

OR
OR
As per my preferences
Profile
Location
Work from home
Part Time
Stipend
Salary
Experience
All Filters
Latest Engineering Intern Jobs
ImmersiWorks Games
EstateBetter Technologies
Enord Private Limited
Qrata
Assocom Foods Private Limited
Myriad Quest Pvt Ltd
Grade Up Assignment
Meru Technosoft Private Limited
ALMI Blogging School Pro (Almi Production Land Solar Private Limited)
Tripple One Solutions
Get FREE Internship and Job Preparation training
Gain a competitive edge with Internshala
4-8 weeks
Placement Assistance
Join
and build your dream career
Trekion AI
VIZON
VIZON
VIZON
VIZON
VIZON
VIZON
VIZON
VIZON
VIZON
FileSure India Private Limited
VIZON
VIZON
VIZON
VIZON
Kweesha
STEMpedia
Aaradhyaa & Co.
AndOr Communications Private Limited
Maxgen Technologies Private Limited
RSVR Technlogies Private Limited
Planys Technologies Private Limited
Megaminds IT Services
CBS Ventures
Inorbvict Healthcare India Private Limited
CyberFrat
Energy Alternatives India
Tech Analogy
Requin Solutions Private Limited
Arhant Solutions
Cartosense
Node Urban Lab
Arhant Solutions
OMNIDYA TECH LLP
BitBison Private Limited
PadosiAgent ServTech Pvt Ltd
Arhant Solutions
Inspire Global
Subinfra Project Management Private Limited
Marpu Foundation

In [33]:
soup.find_all('h2', class_='job-internship-name')

[<h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/2d-game-concept-artist-interactive-internship-in-bangalore-at-immersiworks-games1775734414" id="job_title" target="_blank">2D Game Concept Artist (Interactive)</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/operations-internship-in-indore-at-estatebetter-technologies1773927528" id="job_title" target="_blank">Operations</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/uav-system-internship-in-delhi-at-enord-private-limited1776064835" id="job_title" target="_blank">UAV System</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/qa-tester-internship-in-mumbai-at-qrata1774258048" id="job_title" target="_blank">QA Tester</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/quality-assurance-production-manager-internship-in-greater-noida-at-assocom-foods-private-limited1775111169" id="job_title" target="_blank">Quality Assurance &amp; Production Manager</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/3d-designing-luxury-product-design-internship-in-delhi-at-myriad-quest-pvt-ltd1774865990" id="job_title" target="_blank">3D Designing (Luxury Product Design)</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-part-time-mechanical-engineering-internship-at-grade-up-assignment1776077067" id="job_title" target="_blank">Mechanical Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-accounting-software-tester-internship-at-meru-technosoft-private-limited1776079790" id="job_title" target="_blank">Accounting Software Tester</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/web-development-internship-in-chennai-at-almi-blogging-school-pro-almi-production-land-solar-private-limited1776077904" id="job_title" target="_blank">Web Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-web-development-internship-at-tripple-one-solutions1776084885" id="job_title" target="_blank">Web Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/robotics-data-engineering-internship-in-bangalore-at-trekion-ai1776062326" id="job_title" target="_blank">Robotics Data Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-embedded-systems-internship-at-vizon1775608275" id="job_title" target="_blank">Embedded Systems</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-backend-development-internship-at-vizon1775608222" id="job_title" target="_blank">Backend Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-software-development-internship-at-vizon1775608161" id="job_title" target="_blank">Software Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-front-end-development-internship-at-vizon1775608135" id="job_title" target="_blank">Front End Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/web-development-internship-in-multiple-locations-at-vizon1775221357" id="job_title" target="_blank">Web Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-web-development-internship-at-vizon1775221012" id="job_title" target="_blank">Web Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-game-development-internship-at-vizon1775220935" id="job_title" target="_blank">Game Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/cad-design-internship-in-multiple-locations-at-vizon1775220493" id="job_title" target="_blank">CAD Design</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-cad-design-internship-at-vizon1775220415" id="job_title" target="_blank">CAD Design</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-tech-support-operations-internship-at-filesure-india-private-limited1775120738" id="job_title" target="_blank">Tech Support &amp; Operations</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/3d-designer-internship-in-dehradun-at-vizon1775102608" id="job_title" target="_blank">3D Designer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/linux-engineer-internship-in-dehradun-at-vizon1774931353" id="job_title" target="_blank">Linux Engineer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/full-stack-development-internship-in-dehradun-at-vizon1774398659" id="job_title" target="_blank">Full Stack Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/electronics-engineering-internship-in-dehradun-at-vizon1773347568" id="job_title" target="_blank">Electronics Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/web-development-internship-in-lucknow-at-kweesha1775992811" id="job_title" target="_blank">Web Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/ai-and-robotics-trainer-internship-in-multiple-locations-at-stempedia1776071317" id="job_title" target="_blank">AI And Robotics Trainer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/electrical-engineering-internship-in-mumbai-at-aaradhyaa-co1776053422" id="job_title" target="_blank">Electrical Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/app-store-optimization-specialist-internship-in-noida-at-andor-communications-private-limited1775831305" id="job_title" target="_blank">App Store Optimization Specialist</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/part-time-python-developer-internship-in-ahmedabad-at-maxgen-technologies-private-limited1776065371" id="job_title" target="_blank">Python Developer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-manual-testing-internship-at-rsvr-technlogies-private-limited1776068300" id="job_title" target="_blank">Manual Testing</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/devops-internship-in-chennai-at-planys-technologies-private-limited1776056014" id="job_title" target="_blank">DevOps</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/work-from-home-electrical-and-electronics-engineering-research-associate-internship-at-megaminds-it-services1776060057" id="job_title" target="_blank">Electrical And Electronics Engineering Research Associate</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/it-assistant-internship-in-kochi-at-cbs-ventures1776057063" id="job_title" target="_blank">IT Assistant</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/python-ai-developer-internship-in-pune-at-inorbvict-healthcare-india-private-limited1776059331" id="job_title" target="_blank">Python AI Developer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/reactjs-development-internship-in-jaipur-at-cyberfrat1775805916" id="job_title" target="_blank">ReactJS Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/biochemistry-internship-in-chennai-at-energy-alternatives-india1775719107" id="job_title" target="_blank">Biochemistry</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/technical-operations-internship-in-ahmedabad-at-tech-analogy1775478574" id="job_title" target="_blank">Technical Operations</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/subject-matter-expert-civil-engineering-internship-in-jaipur-at-requin-solutions-private-limited1775116602" id="job_title" target="_blank">Subject Matter Expert (Civil Engineering)</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/aws-devops-engineer-internship-in-ahmedabad-at-arhant-solutions1774974857" id="job_title" target="_blank">AWS DevOps Engineer</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/quality-regulatory-medical-devices-internship-in-bangalore-at-cartosense1775731718" id="job_title" target="_blank">Quality &amp; Regulatory (Medical Devices)</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/architecture-internship-in-lucknow-at-shams-uddin1774360688" id="job_title" target="_blank">Architecture</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/mobile-app-development-internship-in-ahmedabad-at-arhant-solutions1774973731" id="job_title" target="_blank">Mobile App Development</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/cad-design-internship-in-ahmedabad-at-omnidya-tech-llp1774342077" id="job_title" target="_blank">CAD Design</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/electronics-engineering-internship-in-pune-at-bitbison-private-limited1775556184" id="job_title" target="_blank">Electronics Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/flutter-devlopment-internship-in-ahmedabad-at-padosiagent-servtech-pvt-ltd1775129648" id="job_title" target="_blank">Flutter Devlopment</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/database-system-architect-internship-in-ahmedabad-at-arhant-solutions1775017176" id="job_title" target="_blank">Database/System Architect</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/part-time-electronics-engineering-internship-in-multiple-locations-at-inspire-global1775305616" id="job_title" target="_blank">Electronics Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/civil-engineering-internship-in-gurgaon-at-subinfra-project-management-private-limited1775759877" id="job_title" target="_blank">Civil Engineering</a>
 </h2>,
 <h2 class="job-internship-name">
 <a class="job-title-href" href="/internship/detail/student-volunteer-internship-in-hyderabad-at-marpu-foundation1775108609" id="job_title" target="_blank">Student Volunteer</a>
 </h2>]

In [31]:
len(soup.find_all('h2', class_='job-internship-name'))

50

In [36]:
soup.find_all('span', class_='pill pgc-2-pill')

[<span class="pill pgc-2-pill">⭐ 4.5</span>,
 <span class="pill pgc-2-pill">
 <div class="pill-content">
 <img alt="icon calendar" src="https://internshala.com/static/images/pgc/ic-calendar.png"/>
 <p>4-8 weeks</p>
 </div>
 </span>,
 <span class="pill pgc-2-pill">
 <div class="pill-content">
 <img alt="icon" src="https://internshala.com/static/images/pgc/pgc_card_native_2/placement_assistance.svg"/>
 <p>Placement Assistance</p>
 </div>
 </span>]

In [35]:
len(soup.find_all('span', class_='pill pgc-2-pill'))

3

In [47]:
company=soup.find_all('div', class_='individual_internship')

In [48]:
len(company)

51

In [98]:
name=[]
hiring=[]
stipend=[]
loc=[]
old=[]

for i in company:
  job_title_tag = i.find('h2', class_='job-internship-name')
  name.append(job_title_tag.text.strip() if job_title_tag else "N/A")

  job_title_tag1 = i.find('div', class_='actively-hiring-badge')
  hiring.append(job_title_tag1.text.strip() if job_title_tag1 else "N/A")

  job_title_tag1 = i.find('span', class_='stipend')
  stipend.append(job_title_tag1.text.strip() if job_title_tag1 else "N/A")

  # Extract location
  location_tag = i.find('div', class_='locations')
  loc.append(location_tag.find('a').text.strip() if location_tag and location_tag.find('a') else "N/A")

  # Extract posting age
  old_tag = i.find('div', class_='status-info')
  old.append(old_tag.find('span').text.strip() if old_tag and old_tag.find('span') else "N/A")

d={'name':name, 'hiring':hiring, 'stipend':stipend, 'location':loc, 'posted_ago':old}
df=pd.DataFrame(d)
df

,name,hiring,stipend,location,posted_ago
0,2D Game Concept Artist (Interactive),Actively hiring,"₹ 10,000 - 12,000 /month",Bangalore,4 days ago
1,Operations,Actively hiring,"₹ 15,000 - 20,000 /month",Indore,N/A
2,UAV System,N/A,"₹ 5,000 /month",Delhi,N/A
3,QA Tester,Actively hiring,"₹ 7,000 - 10,000 /month",Mumbai,N/A
4,Quality Assurance & Production Manager,Actively hiring,"₹ 6,000 - 17,000 /month",Greater Noida,N/A
5,3D Designing (Luxury Product Design),Actively hiring,"₹ 10,000 - 15,000 /month",Delhi,N/A
6,Mechanical Engineering,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
7,Accounting Software Tester,Actively hiring,"₹ 2,500 - 3,000 /month",Work from home,N/A
8,Web Development,Actively hiring,"₹ 3,000 - 6,000 /month",Chennai,N/A
9,Web Development,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
10,N/A,N/A,N/A,N/A,N/A
11,Robotics Data Engineering,N/A,"₹ 15,000 - 20,000 /month",Bangalore,N/A
12,Embedded Systems,N/A,"₹ 14,000 - 22,000 /month",Work from home,5 days ago
13,Backend Development,N/A,"₹ 11,000 - 17,000 /month",Work from home,5 days ago
14,Software Development,N/A,"₹ 11,000 - 17,000 /month",Work from home,5 days ago
15,Front End Development,N/A,"₹ 12,000 - 20,000 /month",Work from home,5 days ago
16,Web Development,N/A,"₹ 12,000 - 20,000 /month","Dehradun, Bangalore",N/A
17,Web Development,N/A,"₹ 10,000 - 20,000 /month",Work from home,N/A
18,Game Development,N/A,"₹ 15,000 - 20,000 /month",Work from home,N/A
19,CAD Design,N/A,"₹ 11,000 - 20,000 /month","Dehradun, Bangalore",N/A
20,CAD Design,N/A,"₹ 11,000 - 20,000 /month",Work from home,N/A
21,Tech Support & Operations,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
22,3D Designer,N/A,"₹ 12,000 - 21,000 /month",Dehradun,N/A
23,Linux Engineer,N/A,"₹ 12,000 - 23,000 /month",Dehradun,N/A
24,Full Stack Development,N/A,"₹ 12,000 - 20,000 /month",Dehradun,N/A
25,Electronics Engineering,N/A,"₹ 12,000 - 28,000 /month",Dehradun,N/A
26,Web Development,Actively hiring,"₹ 8,600 - 13,500 /month",Lucknow,N/A
27,AI And Robotics Trainer,Actively hiring,"₹ 10,000 - 15,000 /month","Ambala, Faridabad, Gurgaon, Jind, Kurukshetra,...",N/A
28,Electrical Engineering,Actively hiring,"₹ 16,000 - 21,000 /month",Mumbai,N/A
29,App Store Optimization Specialist,Actively hiring,"₹ 20,000 - 20,001 /month",Noida,N/A
30,Python Developer,Actively hiring,"₹ 5,000 - 12,000 /month",Ahmedabad,N/A
31,Manual Testing,Actively hiring,"₹ 15,000 /month",Work from home,N/A
32,DevOps,Actively hiring,"₹ 12,500 - 15,000 /month",Chennai,N/A
33,Electrical And Electronics Engineering Researc...,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
34,IT Assistant,Actively hiring,"₹ 7,000 - 10,000 /month",Kochi,N/A
35,Python AI Developer,Actively hiring,"₹ 6,000 - 6,001 /month",Pune,N/A
36,ReactJS Development,Actively hiring,"₹ 2,000 /month",Jaipur,3 days ago
37,Biochemistry,Actively hiring,"₹ 15,000 - 20,000 /month",Chennai,4 days ago
38,Technical Operations,Actively hiring,"₹ 5,000 - 10,000 /month",Ahmedabad,7 days ago
39,Subject Matter Expert (Civil Engineering),Actively hiring,"₹ 10,000 - 12,000 /month",Jaipur,N/A
40,AWS DevOps Engineer,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
41,Quality & Regulatory (Medical Devices),Actively hiring,"₹ 10,000 /month",Bangalore,4 days ago
42,Architecture,Actively hiring,"₹ 8,000 /month",Lucknow,N/A
43,Mobile App Development,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
44,CAD Design,Actively hiring,"₹ 10,001 - 20,000 /month",Ahmedabad,N/A
45,Electronics Engineering,Actively hiring,"₹ 2,000 - 3,000 /month",Pune,6 days ago
46,Flutter Devlopment,Actively hiring,"₹ 5,000 - 8,000 /month",Ahmedabad,N/A
47,Database/System Architect,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
48,Electronics Engineering,Actively hiring,"₹ 7,000 - 15,000 /month","Navi Mumbai, Mumbai, Panvel Sub-District, Panvel",N/A
49,Civil Engineering,Actively hiring,"₹ 12,000 - 15,000 /month",Gurgaon,3 days ago
50,Student Volunteer,Actively hiring,Unpaid,Hyderabad,N/A

In [96]:
company[0].find_all('div',class_='detail-row-1')

[<div class="detail-row-1">
 <!-- location -->
 <div class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Bangalore</a> </span>
 </div>
 <!-- /location -->
 <!-- STIPEND -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="stipend">₹ 10,000 - 12,000 /month</span> </div>
 <!-- /stipend -->
 <!-- duration -->
 <div class="row-1-item">
 <i class="ic-16-calendar"></i>
 <span>3 Months</span>
 </div>
 <!-- /duration -->
 </div>]

In [94]:
len(company[0].find_all('div',class_='skill_container'))

5

In [100]:
df.shape

(51, 5)

In [111]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

final=pd.DataFrame()

for j in range(1,11):
  url='https://internshala.com/internships/engineering-internship/page-{}'.format(j)
  headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
  webpage = requests.get(url, headers=headers).text

  soup=BeautifulSoup(webpage, 'lxml')
  company=soup.find_all('div', class_='individual_internship')

  name=[]
  hiring=[]
  stipend=[]
  loc=[]
  old=[]

  for i in company:
    job_title_tag = i.find('h2', class_='job-internship-name')
    name.append(job_title_tag.text.strip() if job_title_tag else "N/A")

    job_title_tag1 = i.find('div', class_='actively-hiring-badge')
    hiring.append(job_title_tag1.text.strip() if job_title_tag1 else "N/A")

    job_title_tag1 = i.find('span', class_='stipend')
    stipend.append(job_title_tag1.text.strip() if job_title_tag1 else "N/A")

    # Extract location
    location_tag = i.find('div', class_='locations')
    loc.append(location_tag.find('a').text.strip() if location_tag and location_tag.find('a') else "N/A")

    # Extract posting age
    old_tag = i.find('div', class_='status-info')
    old.append(old_tag.find('span').text.strip() if old_tag and old_tag.find('span') else "N/A")

  d={'name':name, 'hiring':hiring, 'stipend':stipend, 'location':loc, 'posted_ago':old}
  df=pd.DataFrame(d)

  final = pd.concat([final, df], ignore_index=True)

In [107]:
final.shape

(0, 0)

In [112]:
display(final.head(10))

,name,hiring,stipend,location,posted_ago
0,2D Game Concept Artist (Interactive),Actively hiring,"₹ 10,000 - 12,000 /month",Bangalore,4 days ago
1,QA Tester,Actively hiring,"₹ 7,000 - 10,000 /month",Mumbai,N/A
2,Operations,Actively hiring,"₹ 15,000 - 20,000 /month",Indore,N/A
3,Quality Assurance & Production Manager,Actively hiring,"₹ 6,000 - 17,000 /month",Greater Noida,N/A
4,UAV System,N/A,"₹ 5,000 /month",Delhi,N/A
5,Mechanical Engineering,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
6,3D Designing (Luxury Product Design),Actively hiring,"₹ 10,000 - 15,000 /month",Delhi,N/A
7,Web Development,Actively hiring,"₹ 8,600 - 13,500 /month",Lucknow,N/A
8,Web Development,Actively hiring,"₹ 3,000 - 6,000 /month",Chennai,N/A
9,Accounting Software Tester,Actively hiring,"₹ 2,500 - 3,000 /month",Work from home,N/A

In [113]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(final)

,name,hiring,stipend,location,posted_ago
0,2D Game Concept Artist (Interactive),Actively hiring,"₹ 10,000 - 12,000 /month",Bangalore,4 days ago
1,QA Tester,Actively hiring,"₹ 7,000 - 10,000 /month",Mumbai,N/A
2,Operations,Actively hiring,"₹ 15,000 - 20,000 /month",Indore,N/A
3,Quality Assurance & Production Manager,Actively hiring,"₹ 6,000 - 17,000 /month",Greater Noida,N/A
4,UAV System,N/A,"₹ 5,000 /month",Delhi,N/A
5,Mechanical Engineering,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
6,3D Designing (Luxury Product Design),Actively hiring,"₹ 10,000 - 15,000 /month",Delhi,N/A
7,Web Development,Actively hiring,"₹ 8,600 - 13,500 /month",Lucknow,N/A
8,Web Development,Actively hiring,"₹ 3,000 - 6,000 /month",Chennai,N/A
9,Accounting Software Tester,Actively hiring,"₹ 2,500 - 3,000 /month",Work from home,N/A
10,N/A,N/A,N/A,N/A,N/A
11,Robotics Data Engineering,N/A,"₹ 15,000 - 20,000 /month",Bangalore,N/A
12,Embedded Systems,N/A,"₹ 14,000 - 22,000 /month",Work from home,5 days ago
13,Backend Development,N/A,"₹ 11,000 - 17,000 /month",Work from home,5 days ago
14,Software Development,N/A,"₹ 11,000 - 17,000 /month",Work from home,5 days ago
15,Front End Development,N/A,"₹ 12,000 - 20,000 /month",Work from home,5 days ago
16,Web Development,N/A,"₹ 12,000 - 20,000 /month","Dehradun, Bangalore",N/A
17,Web Development,N/A,"₹ 10,000 - 20,000 /month",Work from home,N/A
18,Game Development,N/A,"₹ 15,000 - 20,000 /month",Work from home,N/A
19,CAD Design,N/A,"₹ 11,000 - 20,000 /month","Dehradun, Bangalore",N/A
20,CAD Design,N/A,"₹ 11,000 - 20,000 /month",Work from home,N/A
21,Tech Support & Operations,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
22,3D Designer,N/A,"₹ 12,000 - 21,000 /month",Dehradun,N/A
23,Linux Engineer,N/A,"₹ 12,000 - 23,000 /month",Dehradun,N/A
24,Full Stack Development,N/A,"₹ 12,000 - 20,000 /month",Dehradun,N/A
25,Electronics Engineering,N/A,"₹ 12,000 - 28,000 /month",Dehradun,N/A
26,Electrical Engineering,Actively hiring,"₹ 16,000 - 21,000 /month",Mumbai,N/A
27,AI And Robotics Trainer,Actively hiring,"₹ 10,000 - 15,000 /month","Ambala, Faridabad, Gurgaon, Jind, Kurukshetra,...",N/A
28,App Store Optimization Specialist,Actively hiring,"₹ 20,000 - 20,001 /month",Noida,3 days ago
29,DevOps,Actively hiring,"₹ 12,500 - 15,000 /month",Chennai,N/A
30,Manual Testing,Actively hiring,"₹ 15,000 /month",Work from home,N/A
31,Electrical And Electronics Engineering Researc...,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
32,IT Assistant,Actively hiring,"₹ 7,000 - 10,000 /month",Kochi,N/A
33,ReactJS Development,Actively hiring,"₹ 2,000 /month",Jaipur,3 days ago
34,Biochemistry,Actively hiring,"₹ 15,000 - 20,000 /month",Chennai,4 days ago
35,Technical Operations,Actively hiring,"₹ 5,000 - 10,000 /month",Ahmedabad,7 days ago
36,Subject Matter Expert (Civil Engineering),Actively hiring,"₹ 10,000 - 12,000 /month",Jaipur,N/A
37,AWS DevOps Engineer,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
38,Quality & Regulatory (Medical Devices),Actively hiring,"₹ 10,000 /month",Bangalore,4 days ago
39,Architecture,Actively hiring,"₹ 8,000 /month",Lucknow,N/A
40,Mobile App Development,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
41,CAD Design,Actively hiring,"₹ 10,001 - 20,000 /month",Ahmedabad,N/A
42,Electronics Engineering,Actively hiring,"₹ 2,000 - 3,000 /month",Pune,6 days ago
43,Flutter Devlopment,Actively hiring,"₹ 5,000 - 8,000 /month",Ahmedabad,N/A
44,Database/System Architect,Actively hiring,"₹ 3,000 - 10,000 /month",Ahmedabad,N/A
45,Electronics Engineering,Actively hiring,"₹ 7,000 - 15,000 /month","Navi Mumbai, Mumbai, Panvel Sub-District, Panvel",N/A
46,Civil Engineering,Actively hiring,"₹ 12,000 - 15,000 /month",Gurgaon,3 days ago
47,Student Volunteer,Actively hiring,Unpaid,Hyderabad,N/A
48,Mechanical Engineering,Actively hiring,"₹ 17,500 - 20,000 /month",Bangalore,N/A
49,Electronics Engineer - Field Operations Intern,Actively hiring,"₹ 7,000 - 9,000 /month",Hyderabad,4 days ago
50,Operations,Actively hiring,"₹ 5,000 - 10,000 /month","Jabalpur, Nashik, Ludhiana, Nashik Division",N/A
51,Civil Engineering,Actively hiring,"₹ 12,000 - 15,000 /month",Gurgaon,3 days ago
52,Student Volunteer,Actively hiring,Unpaid,Hyderabad,N/A
53,Mechanical Engineering,Actively hiring,"₹ 17,500 - 20,000 /month",Bangalore,N/A
54,Electronics Engineer - Field Operations Intern,Actively hiring,"₹ 7,000 - 9,000 /month",Hyderabad,4 days ago
55,Operations,Actively hiring,"₹ 5,000 - 10,000 /month","Jabalpur, Nashik, Ludhiana, Nashik Division",N/A
56,Front End Development,N/A,"₹ 5,000 - 15,000 /month",Bikaner,N/A
57,Ruby On Rails Development,N/A,"₹ 5,000 /month",Ahmedabad,N/A
58,React Native Development,N/A,"₹ 5,000 - 8,000 /month",Work from home,N/A
59,PHP Development,N/A,"₹ 5,000 - 6,000 /month",Mumbai,N/A
60,Engineering Design,N/A,"₹ 13,000 - 15,000 /month",Noida,N/A
61,N/A,N/A,N/A,N/A,N/A
62,Horticulturist,N/A,"₹ 5,000 - 6,500 /month",Mumbai,N/A
63,Full Stack Development,N/A,"₹ 4,000 - 8,000 /month","Pune, Pimpri-Chinchwad",N/A
64,Production,N/A,"₹ 10,000 - 15,000 /month",Khalapur,N/A
65,Quality Analyst,N/A,Unpaid,Jaipur,N/A
66,CAD Design,N/A,"₹ 5,000 - 12,000 /month",Delhi,N/A
67,Instrumentation And Calibration,N/A,"₹ 5,000 - 10,000 /month",Bangalore,N/A
68,Business Development (Saas/ERP/CRM),N/A,"₹ 8,000 - 15,000 /month","Faridabad, Delhi, Ghaziabad, Gurgaon, Greater ...",N/A
69,AI/ML Engineer,N/A,"₹ 10,000 /month",Hyderabad,N/A
70,QA / Automation Testing,N/A,"₹ 8,000 - 10,000 /month",Work from home,N/A
71,Founders Team,N/A,"₹ 3,000 - 6,000 /month",Mumbai,N/A
72,Growth & Sales (Tech|Remote),N/A,"₹ 5,000 /month",Work from home,N/A
73,Mobile App Development,N/A,"₹ 2,000 - 5,000 /month",Nagpur,N/A
74,Engineering Design,N/A,"₹ 10,000 /month",Bangalore,N/A
75,Web Development,N/A,"₹ 5,000 - 10,000 /month",Jaipur,N/A
76,Software Testing / QA (Manual + API Testing),N/A,"₹ 10,000 - 12,000 /month",Nashik,3 days ago
77,Mobile App Development,N/A,"₹ 8,000 - 10,000 /month",Bhayander,3 days ago
78,Industrial And Production Engineering,N/A,"₹ 7,000 - 8,000 /month",Delhi,3 days ago
79,Engineering Design,N/A,"₹ 10,000 /month",Noida,3 days ago
80,Autocad Fresher,N/A,"₹ 5,000 - 6,000 /month",Agra,4 days ago
81,Site Engineering - Interior Design,N/A,"₹ 10,000 - 18,000 /month",Hyderabad,4 days ago
82,Android App Development,N/A,"₹ 3,000 - 7,000 /month","Ahmedabad, Gandhinagar",4 days ago
83,WordPress Development,N/A,Unpaid,Pune,5 days ago
84,Biotechnology Engineering,N/A,"₹ 15,000 - 17,000 /month",Ahmedabad,5 days ago
85,Photo and Video Editor,N/A,"₹ 8,000 - 10,000 /month",Delhi,5 days ago
86,Junior Graphic Designer - Work From Our Office...,N/A,"₹ 5,000 - 10,000 /month",Gurgaon,5 days ago
87,Civil Engineering,N/A,"₹ 10,000 - 12,000 /month",Bangalore,6 days ago
88,PHP Development,N/A,"₹ 2,000 - 3,000 /month",Jaipur,6 days ago
89,Electrical Engineering,N/A,"₹ 16,000 - 20,000 /month",Bangalore,6 days ago
90,Architecture,N/A,"₹ 15,000 - 20,000 /month",Noida,6 days ago
91,Operations & Maintenance (O&M),N/A,"₹ 7,000 /month",Jaipur,7 days ago
92,On-site Session Mentor Volunteer,N/A,Unpaid,Mumbai,7 days ago
93,STEM/Robotics and AI Facilitator/Trainer,N/A,"₹ 5,000 - 12,000 /month",Hyderabad,7 days ago
94,Audit & Assurance,N/A,"₹ 10,000 /month",Ahmedabad,N/A
95,Full Stack Development,N/A,"₹ 3,000 - 5,000 /month",Raipur,N/A
96,Android App Development,N/A,"₹ 3,000 - 5,000 /month",Rajkot,N/A
97,Flutter Development,N/A,"₹ 12,000 - 14,000 /month",Bhopal,N/A
98,Bioprocess/Biochemical Engineer - Upstream & D...,N/A,"₹ 2,000 - 5,000 /month",Mumbai,N/A
99,Information Technology,N/A,"₹ 4,332 - 12,221 /month",Dehradun,N/A
100,Chemistry & Life Sciences,N/A,"₹ 2,500 - 3,000 /month","Pune, Mumbai, Vasai-Virar",N/A
101,Clean Tech Prototype Development,N/A,"₹ 12,000 - 18,000 /month",Bangalore,N/A
102,N/A,N/A,N/A,N/A,N/A
103,Architect,N/A,"₹ 15,000 /month",Bangalore,N/A
104,Design Trainee (Interior Or Architecture),N/A,"₹ 10,000 - 15,000 /month",Delhi,N/A
105,Data Labelling & Testing,N/A,"₹ 10,000 - 13,000 /month",Chennai,N/A
106,3D Artist For Jewelry Rendering,N/A,"₹ 8,000 - 17,000 /month",Mumbai,N/A
107,IT Support,N/A,"₹ 2,000 - 5,000 /month",Vadodara,N/A
108,Industrial And Production Engineering,N/A,"₹ 10,001 /month",Mumbai,N/A
109,Design Solutions Architect,N/A,"₹ 2,000 - 3,000 /month",Indore,N/A
110,Quality Analyst,N/A,"₹ 5,000 - 7,000 /month","Mumbai, Vasai",N/A
111,Content & E-Commerce Management,N/A,"₹ 10,000 - 25,000 /month",Bangalore,N/A
112,Product Design (AutoCAD/Solidworks),N/A,"₹ 2,000 /month",Bhopal,N/A
113,Electronics,N/A,"₹ 2,000 /month",Bhopal,N/A
114,Quantum Computing,N/A,"₹ 5,500 - 9,000 /month",Mumbai,N/A
115,Electrical Engineering,N/A,"₹ 3,000 - 5,000 /month","Ahmedabad, Gandhinagar, Nadiad, Surat, Vadodara",N/A
116,Electronics Engineering,N/A,"₹ 2,000 - 5,000 /month","Ahmedabad, Gandhinagar, Himmatnagar",N/A
117,Technical Officer - Valuations,N/A,"₹ 8,000 - 15,000 /month","Ajmer, Bhilwara, Bikaner, Beawar, Jodhpur, Sir...",N/A
118,Architecture,N/A,"₹ 3,000 - 6,000 /month",Nashik,N/A
119,Founders Office,N/A,"₹ 2,000 - 2,500 /month",Bangalore,N/A
120,Content Writer,N/A,"₹ 10,000 - 12,000 /month","Pune, Kharadi",N/A
121,Biotechnology Engineering,N/A,"₹ 8,500 - 9,500 /month",Mumbai,N/A
122,Structural Engineer,N/A,"₹ 7,000 - 7,500 /month",Ahmedabad,N/A
123,Site Supervisor,N/A,"₹ 8,000 - 15,000 /month",Mumbai,N/A
124,Architecture,N/A,"₹ 2,000 - 7,000 /month",Work from home,N/A
125,ReactJS Development,N/A,"₹ 5,000 - 10,000 /month",Coimbatore,N/A
126,Full Stack Development,N/A,"₹ 5,000 - 10,000 /month",Jalgaon,N/A
127,Mechanical & Civil Engineering,N/A,"₹ 2,500 - 3,000 /month","Pune, Mumbai, Vasai-Virar",N/A
128,Chemical Engineering,N/A,"₹ 10,000 - 20,000 /month",Jaipur,N/A
129,Solar Business & Strategy,N/A,"₹ 8,000 - 10,000 /month",Faridabad,N/A
130,Civil Engineering,N/A,"₹ 5,000 - 10,000 /month",Jaipur,N/A
131,Mechanical Engineering,N/A,"₹ 7,000 - 13,000 /month",Chinchwad,N/A
132,MERN TECH INTERNS & FULL STACK INTERNSHIP For ...,N/A,Competitive stipend,Bangalore,N/A
133,Electronics Engineer/Intern,N/A,Competitive stipend,Bangalore,N/A
134,NMR System Development Trainees,N/A,Competitive stipend,Bangalore,N/A
135,Project Manager,N/A,Competitive stipend,Maharashtra,N/A
136,Frontend Developer Intern,N/A,Competitive stipend,Work from home,N/A
137,Intern - Frontend Engineer (Fullstack-Oriented),N/A,Competitive stipend,Work from home,N/A
138,Technical Support Intern,N/A,Competitive stipend,Srinagar,N/A
139,Flutter Developer Intern,N/A,Competitive stipend,Work from home,N/A
140,Intern - Climate Accelerator,N/A,Competitive stipend,Maharashtra,N/A
141,Surveyor Intern,N/A,Competitive stipend,Maharashtra,N/A
142,Technical Support Engineer (Pre-Sales) - Compo...,N/A,Competitive stipend,Bangalore,N/A
143,N/A,N/A,N/A,N/A,N/A
144,PHP Developer Intern,N/A,Competitive stipend,Coimbatore,N/A
145,3D Printing,N/A,Competitive stipend,Maharashtra,N/A
146,Engineer Intern,N/A,Competitive stipend,Bangalore,4 days ago
147,"Medior Linux Engineer (part-time, On-site, Sat...",N/A,Competitive stipend,Work from home,4 days ago
148,Manual Testing Intern (Remote),N/A,Competitive stipend,Maharashtra,4 days ago
149,Implementation Engineer,N/A,Competitive stipend,Chennai,6 days ago
150,Intern Intellectual Property (IP) Management,N/A,Competitive stipend,Ahmedabad,7 days ago
151,Seed Technology Intern,N/A,Competitive stipend,Maharashtra,N/A
152,Web Development,Actively hiring,"₹ 5,000 - 10,000 /month",Work from home,N/A
153,Web Development,N/A,"₹ 1,001 - 6,000 /month",Work from home,N/A
154,Full Stack Development,N/A,"₹ 6,000 - 8,000 /month",Work from home,N/A
155,Python Development Intern,N/A,"₹ 5,000 - 7,000 /month",Work from home,N/A
156,Software Development,N/A,"₹ 7,500 /month",Mumbai,N/A
157,Full Stack Development,N/A,"₹ 3,000 - 13,000 /month",Work from home,N/A
158,Software Development,N/A,"₹ 2,000 - 5,000 /month",Work from home,N/A
159,Python Developer,Actively hiring,"₹ 5,000 - 12,000 /month",Ahmedabad,N/A
160,Python Development,Actively hiring,"₹ 5,000 - 12,000 /month",Pune,N/A
161,UAV System,N/A,"₹ 5,000 /month",Delhi,N/A
162,Shopify E-commerce (Kids Brand),N/A,"₹ 2,500 /month",Work from home,N/A
163,Python AI Developer,Actively hiring,"₹ 6,000 - 6,001 /month",Pune,N/A
164,Web Development,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
165,Cyber Security,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
166,Full Stack Development,Actively hiring,"₹ 10,000 - 12,000 /month","Pune, Pimpri-Chinchwad",N/A
167,Web Development,N/A,"₹ 5,000 /month",Mumbai,N/A
168,Ethical Hacker,Actively hiring,"₹ 27,000 /month",Work from home,N/A
169,Blockchain Development,Actively hiring,"₹ 27,000 /month",Work from home,N/A
170,Web Development,N/A,"₹ 10,000 - 12,000 /month",Vadodara,N/A
171,Software Testing,Actively hiring,"₹ 6,000 - 8,000 /month",Work from home,N/A
172,Android App Development,N/A,"₹ 5,000 - 7,000 /month",Ghaziabad,N/A
173,Mechanical Engineering,N/A,"₹ 2,000 - 5,000 /month",Work from home,N/A
174,Flutter Development,Actively hiring,"₹ 10,000 - 15,000 /month",Work from home,N/A
175,Internet Of Things (IoT),Actively hiring,"₹ 10,000 - 12,000 /month",Work from home,N/A
176,Full Stack Development,Actively hiring,"₹ 5,000 - 6,000 /month",Work from home,N/A
177,Java Development,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
178,Python Development,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
179,Cyber Security,Actively hiring,"₹ 5,000 - 6,000 /month",Work from home,N/A
180,Web Development,Actively hiring,"₹ 8,500 - 16,000 /month",Work from home,N/A
181,Python Development,Actively hiring,"₹ 8,500 - 16,000 /month",Work from home,N/A
182,Java Development,Actively hiring,"₹ 8,500 - 16,000 /month",Work from home,N/A
183,Cyber Security,Actively hiring,"₹ 8,500 - 16,000 /month",Work from home,N/A
184,N/A,N/A,N/A,N/A,N/A
185,Full Stack Development,Actively hiring,"₹ 15,000 - 35,000 /month",Work from home,N/A
186,WordPress Web Development,N/A,"₹ 8,000 - 9,000 /month",Work from home,N/A
187,Full Stack Development,Actively hiring,"₹ 5,000 - 8,000 /month","Patna, Bangalore",N/A
188,Product Management,Actively hiring,"₹ 30,000 /month",Surat,N/A
189,Embedded Hardware,Actively hiring,"₹ 17,500 - 20,000 /month",Bangalore,N/A
190,Web Development,Actively hiring,"₹ 15,000 - 20,000 /month",Mumbai,N/A
191,Mobile App Testing,Actively hiring,"₹ 3,000 - 4,000 /month",Work from home,N/A
192,Software Engineer,Actively hiring,"₹ 15,000 - 18,000 /month",Noida,N/A
193,Java Development,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
194,Python Development,Actively hiring,"₹ 10,000 - 20,000 /month",Work from home,N/A
195,Product Testing,Actively hiring,"₹ 3,000 - 3,001 /month",Work from home,N/A
196,Web Development,N/A,"₹ 6,000 - 13,000 /month",Ahmedabad,3 days ago
197,Artificial Intelligence,Actively hiring,"₹ 8,000 - 15,000 /month",Chennai,3 days ago
198,Mechanical Engineering,N/A,"₹ 8,000 - 12,000 /month",Chennai,3 days ago
199,AI-Robotics Trainer,N/A,"₹ 8,000 - 12,000 /month",Lucknow,3 days ago
200,Thermal Engineering,N/A,"₹ 7,000 - 10,000 /month",Work from home,3 days ago
201,Cyber Security Trainee,N/A,"₹ 3,500 - 4,500 /month",Kota,3 days ago
202,Embedded Systems,Actively hiring,"₹ 17,000 - 20,000 /month",Gurgaon,3 days ago
203,Python/Django & React Engineering,N/A,"₹ 10,000 /month",Delhi,3 days ago
204,Cloud Computing,Actively hiring,"₹ 7,000 - 18,000 /month",Work from home,3 days ago
205,Junior Architect,N/A,"₹ 10,000 /month",Delhi,3 days ago
206,Naval Architecture & Ocean Engineering,Actively hiring,"₹ 8,000 - 16,000 /month",Work from home,3 days ago
207,Internet Of Things (IoT),Actively hiring,"₹ 7,000 - 14,000 /month",Work from home,3 days ago
208,Network Engineering,Actively hiring,"₹ 8,000 - 16,000 /month",Work from home,3 days ago
209,Food Processing Engineering,Actively hiring,"₹ 6,000 - 12,000 /month",Work from home,3 days ago
210,Full Stack Developer (AI- Product & Automation),Actively hiring,"₹ 15,000 - 18,000 /month",Work from home,3 days ago
211,IT Support,Actively hiring,"₹ 9,000 - 10,000 /month",Mumbai,3 days ago
212,Sourcing (Material),Actively hiring,"₹ 9,000 - 10,000 /month",Mumbai,3 days ago
213,Product Development (Apparel),Actively hiring,"₹ 9,000 - 10,000 /month",Mumbai,3 days ago
214,Embedded Systems,N/A,"₹ 5,000 - 12,000 /month","Pune, Mumbai",3 days ago
215,Web Development,Actively hiring,"₹ 15,000 - 20,000 /month",Pune,3 days ago
216,Python Development,Actively hiring,"₹ 2,000 /month",Jaipur,3 days ago
217,Web Development,Actively hiring,"₹ 5,000 - 7,000 /month","Mumbai, Dahisar, Mira Bhayandar, Vasai-Virar",3 days ago
218,Product Ambassador,Actively hiring,"₹ 7,000 - 20,000 /month","Chennai, Coimbatore, Erode, Madurai, Manipal, ...",3 days ago
219,UI/UX Testing/IOS Testing,Actively hiring,"₹ 2,500 - 8,000 /month",Work from home,3 days ago
220,Full-Stack Mobile App Developer (Flutter – IOS...,Actively hiring,"₹ 7,000 - 12,000 /month",Work from home,3 days ago
221,Python Developer (Serverless),Actively hiring,"₹ 2,500 - 8,000 /month",Work from home,3 days ago
222,Quantity Surveying & Cost Estimation,Actively hiring,"₹ 8,000 - 12,000 /month",Chennai,3 days ago
223,Building Information Modeling,Actively hiring,"₹ 6,000 - 12,000 /month",Work from home,3 days ago
224,Product Strategy & Market Intelligence (MBA Su...,N/A,"₹ 15,000 - 20,000 /month",Work from home,3 days ago
225,N/A,N/A,N/A,N/A,N/A
226,AI Automation,N/A,"₹ 5,000 - 10,000 /month",Pune,3 days ago
227,CAD Design,Actively hiring,"₹ 6,000 - 12,000 /month",Work from home,3 days ago
228,Bioinformatics,Actively hiring,Unpaid,Work from home,4 days ago
229,Shopify Development,N/A,"₹ 8,000 - 9,000 /month",Mohali,4 days ago
230,Full Stack Development,Actively hiring,Unpaid,Work from home,4 days ago
231,Front End Development,Actively hiring,Unpaid,Work from home,4 days ago
232,Web Development,Actively hiring,Unpaid,Work from home,4 days ago
233,Electronics Engineering,N/A,"₹ 12,000 - 15,000 /month",Bangalore,4 days ago
234,2D Game Concept Artist (Interactive),Actively hiring,"₹ 10,000 - 12,000 /month",Bangalore,4 days ago
235,Product Management,Actively hiring,"₹ 15,000 - 20,000 /month",Delhi,4 days ago
236,MLOps and AI Infra,Actively hiring,"₹ 15,000 /month",Work from home,4 days ago
237,QA Automation,Actively hiring,"₹ 10,000 - 15,000 /month",Bangalore,4 days ago
238,QA/Testing (Web & Mobile),Actively hiring,"₹ 10,000 - 15,000 /month","Chennai, Gurgaon",4 days ago
239,Python Development,Actively hiring,"₹ 7,500 - 15,000 /month",Work from home,4 days ago
240,Full Stack Development,Actively hiring,"₹ 15,000 - 20,000 /month",Gurgaon,4 days ago
241,Full Stack Development,Actively hiring,"₹ 15,000 - 15,001 /month",Pune,4 days ago
242,CRM & Automation Implementation,Actively hiring,"₹ 25,000 /month","Delhi, Ghaziabad, Gurgaon, Noida",4 days ago
243,Biotech Research For Climate Studies,Actively hiring,"₹ 15,000 - 20,000 /month",Chennai,4 days ago
244,Software Development,Actively hiring,"₹ 10,000 - 15,000 /month","Bangalore, Chennai",4 days ago
245,Front End Development,Actively hiring,"₹ 5,000 - 10,000 /month",Mumbai,4 days ago
246,Web Development,Actively hiring,"₹ 10,000 - 25,000 /month",Work from home,4 days ago
247,Computational Designer,Actively hiring,"₹ 20,000 - 25,000 /month",Bangalore,4 days ago
248,Interior Design,Actively hiring,"₹ 6,000 - 12,000 /month",Delhi,4 days ago
249,Interior Design,N/A,"₹ 2,000 - 5,000 /month",Work from home,4 days ago
250,IT And Business Operations | Stakeholder Manag...,N/A,"₹ 10,000 /month",Gurgaon,4 days ago
251,Mobile App Development,Actively hiring,"₹ 5,000 - 5,001 /month",Jaipur,4 days ago
252,Digital Marketing & Sales Intern (B2B | Tech /...,Actively hiring,"₹ 9,000 - 12,000 /month",Work from home,5 days ago
253,React Native Development,Actively hiring,"₹ 15,000 - 25,000 /month",Mumbai,5 days ago
254,PHP Development,N/A,"₹ 1,000 - 1,001 /month",Work from home,5 days ago

In [71]:
if company:
  print(company[0].prettify())
else:
  print("No internship companies found to inspect.")

<div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/internship/detail/2d-game-concept-artist-interactive-internship-in-bangalore-at-immersiworks-games1775734414" data-source_page="search_page" employment_type="internship" id="individual_internship_3111829" internshipid="3111829" sequential_apply_referral="similar_internships">
 <div class="internship_meta duration_meta">
  <div class="internship-heading-container">
   <div class="company">
    <h2 class="job-internship-name">
     <a class="job-title-href" href="/internship/detail/2d-game-concept-artist-interactive-internship-in-bangalore-at-immersiworks-games1775734414" id="job_title" target="_blank">
      2D Game Concept Artist (Interactive)
     </a>
    </h2>
    <div class="heading_6 company_name">
     <div class="company_and_premium">
      <p class="company-name">
       ImmersiWorks Games
      </p>
      <div class="actively-hiring-badge">
       Actively hiring
      </div>
     </div>
    </div>
   </div>
   <div class="internship_logo">
    <img alt="ImmersiWorks Games" src="https://internshala-uploads.internshala.com/logo%2Fe9da0b3cjtq-111378.png.webp"/>
   </div>
  </div>
  <div class="individual_internship_details individual_internship_internship">
   <div class="detail-row-1">
    <!-- location -->
    <div class="row-1-item locations">
     <i class="ic-16-map-pin">
     </i>
     <span>
      <a>
       Bangalore
      </a>
     </span>
    </div>
    <!-- /location -->
    <!-- STIPEND -->
    <div class="row-1-item">
     <i class="ic-16-money">
     </i>
     <span class="stipend">
      ₹ 10,000 - 12,000 /month
     </span>
    </div>
    <!-- /stipend -->
    <!-- duration -->
    <div class="row-1-item">
     <i class="ic-16-calendar">
     </i>
     <span>
      3 Months
     </span>
    </div>
    <!-- /duration -->
   </div>
   <div class="about_job">
    <div class="ic-16-assignment icon">
    </div>
    <div class="text">
     NOTE: This is NOT a Graphic/UI/Web Design role.

We’re looking for a 2D game concept artist to design characters, environments, and visual worlds for interactive game experiences.
You’ll define themes, color systems, and how players visually experience each game - not just create standalone artwork.

GAME ART PORTFOLIO REQUIRED: You should have a portfolio that includes character and/or environment concepts. We’re specifically looking for candidates who have already explored game art or interactive visual experiences.

Location: Bangalore (Hybrid: 1 - 2 days/week preferred)

About ImmersiWorks Games:
At ImmersiWorks Games, we build immersive, real-world (phygital) game experiences where players use their bodies as the controller, combining physical movement with digital gameplay through projectors and depth sensors in a shared space. These are short, high-energy multiplayer experiences designed to be intuitive, social, and engaging from the very first interaction.

What You’ll Do:
Concept &amp; Visual Thinking
1. Design game themes, environments, characters, and props
2. Define color palettes and visual styles
3. Create moodboards and explore different visual directions

Game Art (2D)
Create:
1. Characters, enemies, collectibles
2. Environment elements
3. UI elements
4. Ensure visuals are: Clear and readable
5. Suitable for gameplay

Environment &amp; Depth
1. Design layered scenes (foreground, midground, background)
2. Think about parallax and depth to make 2D feel spatial
3. Create environments that feel immersive, not flat

� Animation (Basic)
Create: - Basic character animations (walk, idle, reactions) - Gameplay effects (hits, bursts, motion cues) - Simple transitions
Focus on: Clarity, Responsiveness, Playfulness
Focus on functionality and player feedback, not complex animation

Experience Thinking
Think beyond assets:
1. What the player sees
2. What they feel
3. What they do next


Who Should Apply
MUST HAVE - Strong drawing / illustration fundamentals - Ability to design both characters AND environments - Understanding of depth, layering, and parallax - Interest in games / interactive experiences - Willingness to learn and work with game engines (Unity or similar) - Ability to think about how art translates into interactive gameplay

GOOD TO HAVE
1. Exposure to game art (sprites, UI, environments)
2. Basic 2D animation skills
3. Basic familiarity with Unity or any game engine
4. Understanding of how assets are used in games
5. Experience with AI tools for art exploration
6. Portfolio showing: Style consistency, Not just standalone artwork

� Tools (any subset is fine)
1. Photoshop / Illustrator
2. After Effects
3. Blender
4. Any AI tools (Midjourney, etc.)

What You’ll Learn:
1. How to design visual systems for games
2. How art impacts real player interaction
3. How to go from: Concept → Gameplay → Experience - Working in a fast, iterative game environmen
    </div>
   </div>
   <div class="job_skills">
    <div class="skill_container">
     <div class="job_skill">
      Adobe Photoshop
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Adobe Illustrator
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Animation
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Game development
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Blender 3D
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Unity Engine
     </div>
     <div class="dot">
     </div>
    </div>
    <div class="skill_container">
     <div class="job_skill">
      Sketching
     </div>
    </div>
    <div class="more">
     +3 more
    </div>
   </div>
   <div class="detail-row-2">
    <div class="color-labels">
     <div class="status-info">
      <i class="ic-16-reschedule">
      </i>
      <span>
       4 days ago
      </span>
     </div>
     <div class="early_applicant_wrapper">
      <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
      <span>
       Be an early applicant
      </span>
     </div>
    </div>
    <div class="gray-labels">
     <div class="ppo_status">
      <i class="ic-24-experience">
      </i>
      <span>
       Job offer upto
       <span style="font-weight: 500;">
        ₹ 3.6LPA
       </span>
       post internship
      </span>
     </div>
    </div>
   </div>
  </div>
 </div>
</div>